type bin_op =
  | Add (* + *)
  | Sub (* - *)
  | Mul (* * *)
  | Div (* / *)
  | Lt (* < *)
  | Gt (* > *)
  | Eq (* = *)
  | Neq (* <> *)
  | Lte (* <= *)
  | Gte (* >= *)
  | And (* && *)
  | Or (* || *)
